### ISSUE TITLE
Oops! Something went wrong.

### ISSUE THREAD

**Issue by EnitLee** [desophos/idleon-saver#22] opened 2021-12-12 21:10 UTC
**Describe the problem**
Oops! Something went wrong after pressing done at the exe path selection.  Idleon is closed and steam is running.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Open IdleonSaver.exe
2. Click on Next twice
3. See error

**Expected behavior**
The loading bar filling up and moving to the next step.

**Log file**
[logs.zip](https://github.com/desophos/idleon-saver/files/7699844/logs.zip)

**Screenshots**
![error](https://user-images.githubusercontent.com/74365459/145729603-20269b40-f93c-4355-92f2-8ac67eafa5c7.PNG)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by desophos** [comment] 2021-12-15 04:47
Duplicate of #14, thank you for the additional data! I honestly have no idea why this error happens, but I'm investigating alternate methods of obtaining the data that would bypass this problem entirely.

**Closed by desophos** 2021-12-15 04:47 UTC
Labels: bug, duplicate

**Comment by desophos** [comment] 2022-01-03 05:32
Please try [version 3.0.0](https://github.com/desophos/idleon-saver/releases/tag/v3.0.0), which should fix this issue.

**Comment by EnitLee** [comment] 2022-01-03 11:32
Fixed! Tyvm!
